# ----------------
# Code Server + HTTPs Proxy
# Base Tag: linuxserver/code-server:amd64-latest
# Docs: https://hub.docker.com/r/linuxserver/code-server
# ----------------

version: "3.3"

services:
  code:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - HOST_GID=${HOST_GID}
        - DEFAULT_USER=${DEFAULT_USER}
        - SUDO_PASSWORD=${SUDO_PASSWORD}
        - CODE_VERSION=${CODE_VERSION}
    image: code.server.sdk
    container_name: code.server
    privileged: false
    user: ${DEFAULT_USER}
    env_file: .env
    ports:
      - ${VIRTUAL_PORT}:8080
      - "5000-5010:5000-5010"
      - "8000-8010:8000-8010"
    networks:
      - code_server
    volumes:
      - ${HOST_CODE_PATH}:${CODE_PATH}:z
      - ./config/config.yaml:/config/config.yaml:ro
      - ./certs:/config/certs:ro
      - config_data:/config/data
      - config_extensions:/config/extensions
      - logs:/config/data/logs
      - logs:/home/${DEFAULT_USER}/.config/code-server/coder-logs
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 32G
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
        window: 60s

volumes:
  config:
  config_data:
  config_extensions:
  logs:

networks:
  code_server:
    driver: bridge
